var filmsData = [
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/Features126/v4/4a/12/d7/4a12d75d-b7f6-5eb0-3c65-5f88879c2402/15013377-ea27-4c23-a2a9-d68d75ae603c.lsr/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/I6dfv7hld3_fZZt-PoYsUQ/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/_dJgnWG8W30_qMRZYCEx-Q/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/IyvoDdhWEjtSADaSryepIw/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/ewq0-5ZSairVdRtcg43s0w/670x377.webp"  
    },
   
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/S4eF69xSeArWZz2DZKaTOQ/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/WTDZpzkQlaatpb1X4w9jZg/670x377.webp"  
    },      
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/GT66HoV8VJL1IZwaqos_TQ/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/kjrFHClZ3Bt-pT0MJnwdFw/670x377.webp"  
    },
    
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/_Kq-GgPdDxxqWtSZ9GbHug/670x377.webp"  
    },
    {
      movieImg:"https://is3-ssl.mzstatic.com/image/thumb/IryLNqf3vJszRupPX70Elg/670x377.webp"  
    },
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/L4WNJNV3nbmyAL6MQSeGuw/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/guRFN8wTcsEevaCqEl9RBA/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/oANBVngpEJDvHRhdyozySA/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/BXmR2-KFYGt0UOGwMaocBg/670x377.webp"  
    },      
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/XiXPs1AKOFQE7cq7AVlJeQ/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/Epzt9WNlE21aE-FNCoVj2w/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/yXhlXOFkS9yJ1kMmOhfIbg/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/vB48H4eBprLJ-WdCBTA6cw/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/_dJgnWG8W30_qMRZYCEx-Q/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/lN-bUPh0Botn7U7jKgbnFg/670x377.webp"  
    },
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/Iz8wdsRXYRysnRRCY0yMrA/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/PzRfPYv8-A3pM1Uafiv1qQ/670x377.webp"  
    },
    {
      movieImg:"https://is3-ssl.mzstatic.com/image/thumb/xwiVfxV1l5Tfy6-1uQ25_Q/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/PsLk5RQuPoAqWJ-lVe1gLQ/670x377.webp"  
    },      
    {
      movieImg:"https://is3-ssl.mzstatic.com/image/thumb/cyRvgYnPlaVn3rN2SDdW1Q/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/2hSgeI8AyyKcpu_6Rhwg1w/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/StRHuSLsy2WhrdoPNZ07xQ/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/I6dfv7hld3_fZZt-PoYsUQ/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/_dJgnWG8W30_qMRZYCEx-Q/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/IyvoDdhWEjtSADaSryepIw/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/ewq0-5ZSairVdRtcg43s0w/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/8593WFOGVTTA1ncIGrL37g/670x377.webp"  
    },
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/vWs6dt5xDhG_DjIoc-89tA/670x377.webp"  
    },
    {
      movieImg:"https://is3-ssl.mzstatic.com/image/thumb/neRAWaMZZ5xVz4fnbFXJUA/670x377.webp"  
    },      
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/jvpbfkNAZaLIN3DZJUDX8Q/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/zRCSBlp0LjwClRXsjyDNYQ/670x377.webp"  
    },     
  
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/L79If4rL5GAF2ffGc7jBRg/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/XtNPMhEaBU1FKkk_QK-DeA/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/D1SCGzM1ESBh-SIkHwcvUQ/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/McXcp2YSeuDh16Oph0nt6g/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/a99v9iRDYcIGof0CvxUUoA/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/P-1f-E_Qew_9syoQd34Wlw/670x377.webp"  
    },
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/GwU4Qm-NLXeNi7M5bxpX-g/670x377.webp"  
    },      
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/K-nsm8mEVNAAnevMTyya7g/670x377.webp"  
    },
    {
      movieImg:"https://is2-ssl.mzstatic.com/image/thumb/SEsiWD2cTDShiJqUtRPAxg/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/5SQrBAWXONSSRweUSmuRyg/670x377.webp"  
    },
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/_WDO4pxq_b43sYn1s-nJQg/670x377.webp"  
    },
    {
      movieImg:"https://is3-ssl.mzstatic.com/image/thumb/kVTKGnVvCdFlB1sZeKa8YQ/670x377.webp"  
    },
    {
      movieImg:"https://is1-ssl.mzstatic.com/image/thumb/QiFf4rD5DY65HbtJUOjE7Q/670x377.webp"  
    },
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/Ro6cUnMcHLf3sEVL38YlRg/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/uBU112xIP48X2tW5EbpGGQ/670x377.webp"  
    },
    {
      movieImg:"https://is5-ssl.mzstatic.com/image/thumb/NHLksWLSZpTcIw36-n7vWA/670x377.webp"  
    },      
    {
      movieImg:"https://is4-ssl.mzstatic.com/image/thumb/rZ34KsuVSjdutVP-0HO95A/670x377.webp"  
    },
    {
      movieImg:"https://is3-ssl.mzstatic.com/image/thumb/HGw-QzsXlYUDp68NCOvxZQ/670x377.webp"  
    },

]
let container = document.getElementById("container")
filmsData.map(function(el){
    let div = document.createElement("div");
    let image = document.createElement("img");
    image.setAttribute("class","image")
    image.src = el.movieImg;
    image.addEventListener("click",function(){
        showData(el);
    })
  
    div.append(image);
    container.append(div)
})
 
function showData(el){
    window.location.href= "cast.html"
}